package com.hello.ble.protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: morpheus/morpheus_ble.proto

public final class MorpheusBle {
  private MorpheusBle() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface WifiEndPointOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string name = 1;
    /**
     * <code>optional string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 1;</code>
     */
    String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional bytes mac = 2;
    /**
     * <code>optional bytes mac = 2;</code>
     */
    boolean hasMac();
    /**
     * <code>optional bytes mac = 2;</code>
     */
    com.google.protobuf.ByteString getMac();
  }
  /**
   * Protobuf type {@code WifiEndPoint}
   */
  public static final class WifiEndPoint extends
      com.google.protobuf.GeneratedMessage
      implements WifiEndPointOrBuilder {
    // Use WifiEndPoint.newBuilder() to construct.
    private WifiEndPoint(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WifiEndPoint(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WifiEndPoint defaultInstance;
    public static WifiEndPoint getDefaultInstance() {
      return defaultInstance;
    }

    public WifiEndPoint getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WifiEndPoint(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              mac_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MorpheusBle.internal_static_WifiEndPoint_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MorpheusBle.internal_static_WifiEndPoint_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              WifiEndPoint.class, Builder.class);
    }

    public static com.google.protobuf.Parser<WifiEndPoint> PARSER =
        new com.google.protobuf.AbstractParser<WifiEndPoint>() {
      public WifiEndPoint parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WifiEndPoint(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<WifiEndPoint> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bytes mac = 2;
    public static final int MAC_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString mac_;
    /**
     * <code>optional bytes mac = 2;</code>
     */
    public boolean hasMac() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes mac = 2;</code>
     */
    public com.google.protobuf.ByteString getMac() {
      return mac_;
    }

    private void initFields() {
      name_ = "";
      mac_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, mac_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, mac_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static WifiEndPoint parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static WifiEndPoint parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static WifiEndPoint parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static WifiEndPoint parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static WifiEndPoint parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static WifiEndPoint parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static WifiEndPoint parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static WifiEndPoint parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static WifiEndPoint parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static WifiEndPoint parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(WifiEndPoint prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code WifiEndPoint}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements WifiEndPointOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MorpheusBle.internal_static_WifiEndPoint_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MorpheusBle.internal_static_WifiEndPoint_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                WifiEndPoint.class, Builder.class);
      }

      // Construct using MorpheusBle.WifiEndPoint.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        mac_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MorpheusBle.internal_static_WifiEndPoint_descriptor;
      }

      public WifiEndPoint getDefaultInstanceForType() {
        return WifiEndPoint.getDefaultInstance();
      }

      public WifiEndPoint build() {
        WifiEndPoint result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public WifiEndPoint buildPartial() {
        WifiEndPoint result = new WifiEndPoint(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.mac_ = mac_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof WifiEndPoint) {
          return mergeFrom((WifiEndPoint)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(WifiEndPoint other) {
        if (other == WifiEndPoint.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasMac()) {
          setMac(other.getMac());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        WifiEndPoint parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (WifiEndPoint) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string name = 1;
      private Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // optional bytes mac = 2;
      private com.google.protobuf.ByteString mac_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes mac = 2;</code>
       */
      public boolean hasMac() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes mac = 2;</code>
       */
      public com.google.protobuf.ByteString getMac() {
        return mac_;
      }
      /**
       * <code>optional bytes mac = 2;</code>
       */
      public Builder setMac(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        mac_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes mac = 2;</code>
       */
      public Builder clearMac() {
        bitField0_ = (bitField0_ & ~0x00000002);
        mac_ = getDefaultInstance().getMac();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:WifiEndPoint)
    }

    static {
      defaultInstance = new WifiEndPoint(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:WifiEndPoint)
  }

  public interface SelectedWifiEndPointOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .WifiEndPoint endPoint = 1;
    /**
     * <code>optional .WifiEndPoint endPoint = 1;</code>
     */
    boolean hasEndPoint();
    /**
     * <code>optional .WifiEndPoint endPoint = 1;</code>
     */
    WifiEndPoint getEndPoint();
    /**
     * <code>optional .WifiEndPoint endPoint = 1;</code>
     */
    WifiEndPointOrBuilder getEndPointOrBuilder();

    // optional string password = 2;
    /**
     * <code>optional string password = 2;</code>
     */
    boolean hasPassword();
    /**
     * <code>optional string password = 2;</code>
     */
    String getPassword();
    /**
     * <code>optional string password = 2;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * Protobuf type {@code SelectedWifiEndPoint}
   */
  public static final class SelectedWifiEndPoint extends
      com.google.protobuf.GeneratedMessage
      implements SelectedWifiEndPointOrBuilder {
    // Use SelectedWifiEndPoint.newBuilder() to construct.
    private SelectedWifiEndPoint(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SelectedWifiEndPoint(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SelectedWifiEndPoint defaultInstance;
    public static SelectedWifiEndPoint getDefaultInstance() {
      return defaultInstance;
    }

    public SelectedWifiEndPoint getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SelectedWifiEndPoint(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              WifiEndPoint.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = endPoint_.toBuilder();
              }
              endPoint_ = input.readMessage(WifiEndPoint.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(endPoint_);
                endPoint_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              password_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MorpheusBle.internal_static_SelectedWifiEndPoint_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MorpheusBle.internal_static_SelectedWifiEndPoint_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SelectedWifiEndPoint.class, Builder.class);
    }

    public static com.google.protobuf.Parser<SelectedWifiEndPoint> PARSER =
        new com.google.protobuf.AbstractParser<SelectedWifiEndPoint>() {
      public SelectedWifiEndPoint parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SelectedWifiEndPoint(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<SelectedWifiEndPoint> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .WifiEndPoint endPoint = 1;
    public static final int ENDPOINT_FIELD_NUMBER = 1;
    private WifiEndPoint endPoint_;
    /**
     * <code>optional .WifiEndPoint endPoint = 1;</code>
     */
    public boolean hasEndPoint() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .WifiEndPoint endPoint = 1;</code>
     */
    public WifiEndPoint getEndPoint() {
      return endPoint_;
    }
    /**
     * <code>optional .WifiEndPoint endPoint = 1;</code>
     */
    public WifiEndPointOrBuilder getEndPointOrBuilder() {
      return endPoint_;
    }

    // optional string password = 2;
    public static final int PASSWORD_FIELD_NUMBER = 2;
    private Object password_;
    /**
     * <code>optional string password = 2;</code>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string password = 2;</code>
     */
    public String getPassword() {
      Object ref = password_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string password = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      endPoint_ = WifiEndPoint.getDefaultInstance();
      password_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, endPoint_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPasswordBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, endPoint_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPasswordBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static SelectedWifiEndPoint parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SelectedWifiEndPoint parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SelectedWifiEndPoint parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SelectedWifiEndPoint parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SelectedWifiEndPoint parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SelectedWifiEndPoint parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static SelectedWifiEndPoint parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static SelectedWifiEndPoint parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static SelectedWifiEndPoint parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SelectedWifiEndPoint parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(SelectedWifiEndPoint prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SelectedWifiEndPoint}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements SelectedWifiEndPointOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MorpheusBle.internal_static_SelectedWifiEndPoint_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MorpheusBle.internal_static_SelectedWifiEndPoint_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SelectedWifiEndPoint.class, Builder.class);
      }

      // Construct using MorpheusBle.SelectedWifiEndPoint.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getEndPointFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (endPointBuilder_ == null) {
          endPoint_ = WifiEndPoint.getDefaultInstance();
        } else {
          endPointBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MorpheusBle.internal_static_SelectedWifiEndPoint_descriptor;
      }

      public SelectedWifiEndPoint getDefaultInstanceForType() {
        return SelectedWifiEndPoint.getDefaultInstance();
      }

      public SelectedWifiEndPoint build() {
        SelectedWifiEndPoint result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SelectedWifiEndPoint buildPartial() {
        SelectedWifiEndPoint result = new SelectedWifiEndPoint(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (endPointBuilder_ == null) {
          result.endPoint_ = endPoint_;
        } else {
          result.endPoint_ = endPointBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.password_ = password_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SelectedWifiEndPoint) {
          return mergeFrom((SelectedWifiEndPoint)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SelectedWifiEndPoint other) {
        if (other == SelectedWifiEndPoint.getDefaultInstance()) return this;
        if (other.hasEndPoint()) {
          mergeEndPoint(other.getEndPoint());
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000002;
          password_ = other.password_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SelectedWifiEndPoint parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SelectedWifiEndPoint) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .WifiEndPoint endPoint = 1;
      private WifiEndPoint endPoint_ = WifiEndPoint.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          WifiEndPoint, WifiEndPoint.Builder, WifiEndPointOrBuilder> endPointBuilder_;
      /**
       * <code>optional .WifiEndPoint endPoint = 1;</code>
       */
      public boolean hasEndPoint() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .WifiEndPoint endPoint = 1;</code>
       */
      public WifiEndPoint getEndPoint() {
        if (endPointBuilder_ == null) {
          return endPoint_;
        } else {
          return endPointBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .WifiEndPoint endPoint = 1;</code>
       */
      public Builder setEndPoint(WifiEndPoint value) {
        if (endPointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          endPoint_ = value;
          onChanged();
        } else {
          endPointBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .WifiEndPoint endPoint = 1;</code>
       */
      public Builder setEndPoint(
          WifiEndPoint.Builder builderForValue) {
        if (endPointBuilder_ == null) {
          endPoint_ = builderForValue.build();
          onChanged();
        } else {
          endPointBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .WifiEndPoint endPoint = 1;</code>
       */
      public Builder mergeEndPoint(WifiEndPoint value) {
        if (endPointBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              endPoint_ != WifiEndPoint.getDefaultInstance()) {
            endPoint_ =
              WifiEndPoint.newBuilder(endPoint_).mergeFrom(value).buildPartial();
          } else {
            endPoint_ = value;
          }
          onChanged();
        } else {
          endPointBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .WifiEndPoint endPoint = 1;</code>
       */
      public Builder clearEndPoint() {
        if (endPointBuilder_ == null) {
          endPoint_ = WifiEndPoint.getDefaultInstance();
          onChanged();
        } else {
          endPointBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .WifiEndPoint endPoint = 1;</code>
       */
      public WifiEndPoint.Builder getEndPointBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getEndPointFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .WifiEndPoint endPoint = 1;</code>
       */
      public WifiEndPointOrBuilder getEndPointOrBuilder() {
        if (endPointBuilder_ != null) {
          return endPointBuilder_.getMessageOrBuilder();
        } else {
          return endPoint_;
        }
      }
      /**
       * <code>optional .WifiEndPoint endPoint = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          WifiEndPoint, WifiEndPoint.Builder, WifiEndPointOrBuilder>
          getEndPointFieldBuilder() {
        if (endPointBuilder_ == null) {
          endPointBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              WifiEndPoint, WifiEndPoint.Builder, WifiEndPointOrBuilder>(
                  endPoint_,
                  getParentForChildren(),
                  isClean());
          endPoint_ = null;
        }
        return endPointBuilder_;
      }

      // optional string password = 2;
      private Object password_ = "";
      /**
       * <code>optional string password = 2;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public String getPassword() {
        Object ref = password_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public Builder setPassword(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SelectedWifiEndPoint)
    }

    static {
      defaultInstance = new SelectedWifiEndPoint(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SelectedWifiEndPoint)
  }

  public interface MorpheusCommandOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 version = 1;
    /**
     * <code>required int32 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required int32 version = 1;</code>
     */
    int getVersion();

    // required .MorpheusCommand.CommandType type = 2;
    /**
     * <code>required .MorpheusCommand.CommandType type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>required .MorpheusCommand.CommandType type = 2;</code>
     */
    MorpheusCommand.CommandType getType();

    // optional .SelectedWifiEndPoint selectedWIFIEndPoint = 3;
    /**
     * <code>optional .SelectedWifiEndPoint selectedWIFIEndPoint = 3;</code>
     */
    boolean hasSelectedWIFIEndPoint();
    /**
     * <code>optional .SelectedWifiEndPoint selectedWIFIEndPoint = 3;</code>
     */
    SelectedWifiEndPoint getSelectedWIFIEndPoint();
    /**
     * <code>optional .SelectedWifiEndPoint selectedWIFIEndPoint = 3;</code>
     */
    SelectedWifiEndPointOrBuilder getSelectedWIFIEndPointOrBuilder();
  }
  /**
   * Protobuf type {@code MorpheusCommand}
   */
  public static final class MorpheusCommand extends
      com.google.protobuf.GeneratedMessage
      implements MorpheusCommandOrBuilder {
    // Use MorpheusCommand.newBuilder() to construct.
    private MorpheusCommand(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MorpheusCommand(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MorpheusCommand defaultInstance;
    public static MorpheusCommand getDefaultInstance() {
      return defaultInstance;
    }

    public MorpheusCommand getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MorpheusCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              CommandType value = CommandType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                type_ = value;
              }
              break;
            }
            case 26: {
              SelectedWifiEndPoint.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = selectedWIFIEndPoint_.toBuilder();
              }
              selectedWIFIEndPoint_ = input.readMessage(SelectedWifiEndPoint.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(selectedWIFIEndPoint_);
                selectedWIFIEndPoint_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MorpheusBle.internal_static_MorpheusCommand_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MorpheusBle.internal_static_MorpheusCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MorpheusCommand.class, Builder.class);
    }

    public static com.google.protobuf.Parser<MorpheusCommand> PARSER =
        new com.google.protobuf.AbstractParser<MorpheusCommand>() {
      public MorpheusCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MorpheusCommand(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<MorpheusCommand> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code MorpheusCommand.CommandType}
     */
    public enum CommandType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MORPHEUS_COMMAND_SET_TIME = 0;</code>
       */
      MORPHEUS_COMMAND_SET_TIME(0, 0),
      /**
       * <code>MORPHEUS_COMMAND_GET_TIME = 1;</code>
       */
      MORPHEUS_COMMAND_GET_TIME(1, 1),
      /**
       * <code>MORPHEUS_COMMAND_SET_WIFI_ENDPOINT = 2;</code>
       */
      MORPHEUS_COMMAND_SET_WIFI_ENDPOINT(2, 2),
      /**
       * <code>MORPHEUS_COMMAND_GET_WIFI_ENDPOINT = 3;</code>
       */
      MORPHEUS_COMMAND_GET_WIFI_ENDPOINT(3, 3),
      /**
       * <code>MORPHEUS_COMMAND_SET_ALARMS = 4;</code>
       */
      MORPHEUS_COMMAND_SET_ALARMS(4, 4),
      /**
       * <code>MORPHEUS_COMMAND_GET_ALARMS = 5;</code>
       */
      MORPHEUS_COMMAND_GET_ALARMS(5, 5),
      /**
       * <code>MORPHEUS_COMMAND_SWITCH_TO_PAIRING_MODE = 6;</code>
       */
      MORPHEUS_COMMAND_SWITCH_TO_PAIRING_MODE(6, 6),
      /**
       * <code>MORPHEUS_COMMAND_SWITCH_TO_NORMAL_MODE = 7;</code>
       */
      MORPHEUS_COMMAND_SWITCH_TO_NORMAL_MODE(7, 7),
      /**
       * <code>MORPHEUS_COMMAND_START_WIFISCAN = 8;</code>
       */
      MORPHEUS_COMMAND_START_WIFISCAN(8, 8),
      /**
       * <code>MORPHEUS_COMMAND_STOP_WIFISCAN = 9;</code>
       */
      MORPHEUS_COMMAND_STOP_WIFISCAN(9, 9),
      /**
       * <code>MORPHEUS_COMMAND_GET_DEVICE_ID = 10;</code>
       */
      MORPHEUS_COMMAND_GET_DEVICE_ID(10, 10),
      ;

      /**
       * <code>MORPHEUS_COMMAND_SET_TIME = 0;</code>
       */
      public static final int MORPHEUS_COMMAND_SET_TIME_VALUE = 0;
      /**
       * <code>MORPHEUS_COMMAND_GET_TIME = 1;</code>
       */
      public static final int MORPHEUS_COMMAND_GET_TIME_VALUE = 1;
      /**
       * <code>MORPHEUS_COMMAND_SET_WIFI_ENDPOINT = 2;</code>
       */
      public static final int MORPHEUS_COMMAND_SET_WIFI_ENDPOINT_VALUE = 2;
      /**
       * <code>MORPHEUS_COMMAND_GET_WIFI_ENDPOINT = 3;</code>
       */
      public static final int MORPHEUS_COMMAND_GET_WIFI_ENDPOINT_VALUE = 3;
      /**
       * <code>MORPHEUS_COMMAND_SET_ALARMS = 4;</code>
       */
      public static final int MORPHEUS_COMMAND_SET_ALARMS_VALUE = 4;
      /**
       * <code>MORPHEUS_COMMAND_GET_ALARMS = 5;</code>
       */
      public static final int MORPHEUS_COMMAND_GET_ALARMS_VALUE = 5;
      /**
       * <code>MORPHEUS_COMMAND_SWITCH_TO_PAIRING_MODE = 6;</code>
       */
      public static final int MORPHEUS_COMMAND_SWITCH_TO_PAIRING_MODE_VALUE = 6;
      /**
       * <code>MORPHEUS_COMMAND_SWITCH_TO_NORMAL_MODE = 7;</code>
       */
      public static final int MORPHEUS_COMMAND_SWITCH_TO_NORMAL_MODE_VALUE = 7;
      /**
       * <code>MORPHEUS_COMMAND_START_WIFISCAN = 8;</code>
       */
      public static final int MORPHEUS_COMMAND_START_WIFISCAN_VALUE = 8;
      /**
       * <code>MORPHEUS_COMMAND_STOP_WIFISCAN = 9;</code>
       */
      public static final int MORPHEUS_COMMAND_STOP_WIFISCAN_VALUE = 9;
      /**
       * <code>MORPHEUS_COMMAND_GET_DEVICE_ID = 10;</code>
       */
      public static final int MORPHEUS_COMMAND_GET_DEVICE_ID_VALUE = 10;


      public final int getNumber() { return value; }

      public static CommandType valueOf(int value) {
        switch (value) {
          case 0: return MORPHEUS_COMMAND_SET_TIME;
          case 1: return MORPHEUS_COMMAND_GET_TIME;
          case 2: return MORPHEUS_COMMAND_SET_WIFI_ENDPOINT;
          case 3: return MORPHEUS_COMMAND_GET_WIFI_ENDPOINT;
          case 4: return MORPHEUS_COMMAND_SET_ALARMS;
          case 5: return MORPHEUS_COMMAND_GET_ALARMS;
          case 6: return MORPHEUS_COMMAND_SWITCH_TO_PAIRING_MODE;
          case 7: return MORPHEUS_COMMAND_SWITCH_TO_NORMAL_MODE;
          case 8: return MORPHEUS_COMMAND_START_WIFISCAN;
          case 9: return MORPHEUS_COMMAND_STOP_WIFISCAN;
          case 10: return MORPHEUS_COMMAND_GET_DEVICE_ID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CommandType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CommandType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CommandType>() {
              public CommandType findValueByNumber(int number) {
                return CommandType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return MorpheusCommand.getDescriptor().getEnumTypes().get(0);
      }

      private static final CommandType[] VALUES = values();

      public static CommandType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private CommandType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MorpheusCommand.CommandType)
    }

    private int bitField0_;
    // required int32 version = 1;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required int32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }

    // required .MorpheusCommand.CommandType type = 2;
    public static final int TYPE_FIELD_NUMBER = 2;
    private CommandType type_;
    /**
     * <code>required .MorpheusCommand.CommandType type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .MorpheusCommand.CommandType type = 2;</code>
     */
    public CommandType getType() {
      return type_;
    }

    // optional .SelectedWifiEndPoint selectedWIFIEndPoint = 3;
    public static final int SELECTEDWIFIENDPOINT_FIELD_NUMBER = 3;
    private SelectedWifiEndPoint selectedWIFIEndPoint_;
    /**
     * <code>optional .SelectedWifiEndPoint selectedWIFIEndPoint = 3;</code>
     */
    public boolean hasSelectedWIFIEndPoint() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .SelectedWifiEndPoint selectedWIFIEndPoint = 3;</code>
     */
    public SelectedWifiEndPoint getSelectedWIFIEndPoint() {
      return selectedWIFIEndPoint_;
    }
    /**
     * <code>optional .SelectedWifiEndPoint selectedWIFIEndPoint = 3;</code>
     */
    public SelectedWifiEndPointOrBuilder getSelectedWIFIEndPointOrBuilder() {
      return selectedWIFIEndPoint_;
    }

    private void initFields() {
      version_ = 0;
      type_ = CommandType.MORPHEUS_COMMAND_SET_TIME;
      selectedWIFIEndPoint_ = SelectedWifiEndPoint.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, type_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, selectedWIFIEndPoint_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, selectedWIFIEndPoint_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static MorpheusCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MorpheusCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MorpheusCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MorpheusCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MorpheusCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static MorpheusCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static MorpheusCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static MorpheusCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static MorpheusCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static MorpheusCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(MorpheusCommand prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MorpheusCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements MorpheusCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MorpheusBle.internal_static_MorpheusCommand_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MorpheusBle.internal_static_MorpheusCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MorpheusCommand.class, Builder.class);
      }

      // Construct using MorpheusBle.MorpheusCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSelectedWIFIEndPointFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = CommandType.MORPHEUS_COMMAND_SET_TIME;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (selectedWIFIEndPointBuilder_ == null) {
          selectedWIFIEndPoint_ = SelectedWifiEndPoint.getDefaultInstance();
        } else {
          selectedWIFIEndPointBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MorpheusBle.internal_static_MorpheusCommand_descriptor;
      }

      public MorpheusCommand getDefaultInstanceForType() {
        return MorpheusCommand.getDefaultInstance();
      }

      public MorpheusCommand build() {
        MorpheusCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MorpheusCommand buildPartial() {
        MorpheusCommand result = new MorpheusCommand(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (selectedWIFIEndPointBuilder_ == null) {
          result.selectedWIFIEndPoint_ = selectedWIFIEndPoint_;
        } else {
          result.selectedWIFIEndPoint_ = selectedWIFIEndPointBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MorpheusCommand) {
          return mergeFrom((MorpheusCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MorpheusCommand other) {
        if (other == MorpheusCommand.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasSelectedWIFIEndPoint()) {
          mergeSelectedWIFIEndPoint(other.getSelectedWIFIEndPoint());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MorpheusCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MorpheusCommand) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 version = 1;
      private int version_ ;
      /**
       * <code>required int32 version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }

      // required .MorpheusCommand.CommandType type = 2;
      private CommandType type_ = CommandType.MORPHEUS_COMMAND_SET_TIME;
      /**
       * <code>required .MorpheusCommand.CommandType type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .MorpheusCommand.CommandType type = 2;</code>
       */
      public CommandType getType() {
        return type_;
      }
      /**
       * <code>required .MorpheusCommand.CommandType type = 2;</code>
       */
      public Builder setType(CommandType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .MorpheusCommand.CommandType type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = CommandType.MORPHEUS_COMMAND_SET_TIME;
        onChanged();
        return this;
      }

      // optional .SelectedWifiEndPoint selectedWIFIEndPoint = 3;
      private SelectedWifiEndPoint selectedWIFIEndPoint_ = SelectedWifiEndPoint.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          SelectedWifiEndPoint, SelectedWifiEndPoint.Builder, SelectedWifiEndPointOrBuilder> selectedWIFIEndPointBuilder_;
      /**
       * <code>optional .SelectedWifiEndPoint selectedWIFIEndPoint = 3;</code>
       */
      public boolean hasSelectedWIFIEndPoint() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .SelectedWifiEndPoint selectedWIFIEndPoint = 3;</code>
       */
      public SelectedWifiEndPoint getSelectedWIFIEndPoint() {
        if (selectedWIFIEndPointBuilder_ == null) {
          return selectedWIFIEndPoint_;
        } else {
          return selectedWIFIEndPointBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .SelectedWifiEndPoint selectedWIFIEndPoint = 3;</code>
       */
      public Builder setSelectedWIFIEndPoint(SelectedWifiEndPoint value) {
        if (selectedWIFIEndPointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          selectedWIFIEndPoint_ = value;
          onChanged();
        } else {
          selectedWIFIEndPointBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .SelectedWifiEndPoint selectedWIFIEndPoint = 3;</code>
       */
      public Builder setSelectedWIFIEndPoint(
          SelectedWifiEndPoint.Builder builderForValue) {
        if (selectedWIFIEndPointBuilder_ == null) {
          selectedWIFIEndPoint_ = builderForValue.build();
          onChanged();
        } else {
          selectedWIFIEndPointBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .SelectedWifiEndPoint selectedWIFIEndPoint = 3;</code>
       */
      public Builder mergeSelectedWIFIEndPoint(SelectedWifiEndPoint value) {
        if (selectedWIFIEndPointBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              selectedWIFIEndPoint_ != SelectedWifiEndPoint.getDefaultInstance()) {
            selectedWIFIEndPoint_ =
              SelectedWifiEndPoint.newBuilder(selectedWIFIEndPoint_).mergeFrom(value).buildPartial();
          } else {
            selectedWIFIEndPoint_ = value;
          }
          onChanged();
        } else {
          selectedWIFIEndPointBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .SelectedWifiEndPoint selectedWIFIEndPoint = 3;</code>
       */
      public Builder clearSelectedWIFIEndPoint() {
        if (selectedWIFIEndPointBuilder_ == null) {
          selectedWIFIEndPoint_ = SelectedWifiEndPoint.getDefaultInstance();
          onChanged();
        } else {
          selectedWIFIEndPointBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .SelectedWifiEndPoint selectedWIFIEndPoint = 3;</code>
       */
      public SelectedWifiEndPoint.Builder getSelectedWIFIEndPointBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getSelectedWIFIEndPointFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .SelectedWifiEndPoint selectedWIFIEndPoint = 3;</code>
       */
      public SelectedWifiEndPointOrBuilder getSelectedWIFIEndPointOrBuilder() {
        if (selectedWIFIEndPointBuilder_ != null) {
          return selectedWIFIEndPointBuilder_.getMessageOrBuilder();
        } else {
          return selectedWIFIEndPoint_;
        }
      }
      /**
       * <code>optional .SelectedWifiEndPoint selectedWIFIEndPoint = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          SelectedWifiEndPoint, SelectedWifiEndPoint.Builder, SelectedWifiEndPointOrBuilder>
          getSelectedWIFIEndPointFieldBuilder() {
        if (selectedWIFIEndPointBuilder_ == null) {
          selectedWIFIEndPointBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              SelectedWifiEndPoint, SelectedWifiEndPoint.Builder, SelectedWifiEndPointOrBuilder>(
                  selectedWIFIEndPoint_,
                  getParentForChildren(),
                  isClean());
          selectedWIFIEndPoint_ = null;
        }
        return selectedWIFIEndPointBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:MorpheusCommand)
    }

    static {
      defaultInstance = new MorpheusCommand(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MorpheusCommand)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_WifiEndPoint_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_WifiEndPoint_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SelectedWifiEndPoint_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SelectedWifiEndPoint_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MorpheusCommand_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MorpheusCommand_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\033morpheus/morpheus_ble.proto\")\n\014WifiEnd" +
      "Point\022\014\n\004name\030\001 \001(\t\022\013\n\003mac\030\002 \001(\014\"I\n\024Sele" +
      "ctedWifiEndPoint\022\037\n\010endPoint\030\001 \001(\0132\r.Wif" +
      "iEndPoint\022\020\n\010password\030\002 \001(\t\"\251\004\n\017Morpheus" +
      "Command\022\017\n\007version\030\001 \002(\005\022*\n\004type\030\002 \002(\0162\034" +
      ".MorpheusCommand.CommandType\0223\n\024selected" +
      "WIFIEndPoint\030\003 \001(\0132\025.SelectedWifiEndPoin" +
      "t\"\243\003\n\013CommandType\022\035\n\031MORPHEUS_COMMAND_SE" +
      "T_TIME\020\000\022\035\n\031MORPHEUS_COMMAND_GET_TIME\020\001\022" +
      "&\n\"MORPHEUS_COMMAND_SET_WIFI_ENDPOINT\020\002\022",
      "&\n\"MORPHEUS_COMMAND_GET_WIFI_ENDPOINT\020\003\022" +
      "\037\n\033MORPHEUS_COMMAND_SET_ALARMS\020\004\022\037\n\033MORP" +
      "HEUS_COMMAND_GET_ALARMS\020\005\022+\n\'MORPHEUS_CO" +
      "MMAND_SWITCH_TO_PAIRING_MODE\020\006\022*\n&MORPHE" +
      "US_COMMAND_SWITCH_TO_NORMAL_MODE\020\007\022#\n\037MO" +
      "RPHEUS_COMMAND_START_WIFISCAN\020\010\022\"\n\036MORPH" +
      "EUS_COMMAND_STOP_WIFISCAN\020\t\022\"\n\036MORPHEUS_" +
      "COMMAND_GET_DEVICE_ID\020\n"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_WifiEndPoint_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_WifiEndPoint_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_WifiEndPoint_descriptor,
              new String[] { "Name", "Mac", });
          internal_static_SelectedWifiEndPoint_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_SelectedWifiEndPoint_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SelectedWifiEndPoint_descriptor,
              new String[] { "EndPoint", "Password", });
          internal_static_MorpheusCommand_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_MorpheusCommand_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MorpheusCommand_descriptor,
              new String[] { "Version", "Type", "SelectedWIFIEndPoint", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
